spring:
  config:
    import: optional:file:./smerp/.env[.properties]
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  # 맨 처음 테스트 할 때만 주석 제거 (data.sql파일 위치확인, ddl-auto확인)
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    #defer-datasource-initialization: true # 맨 처음 샘플 데이터 넣을 시 주석 제거
