apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pcochoco/backend:8e5a8d19203b7451846b63f10bf05d9bcf4d3573
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: server_port

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: spring_datasource_url

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: spring_datasource_username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: spring_datasource_password

            - name: SPRING_DATASOURCE_DRIVER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: spring_datasource_driver

            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: encrypt_key

            - name: ENCRYPT_SALT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: encrypt_salt

            - name: QUERYDSLVERSION
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: querydslversion

          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regsecret
