# service
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend #deployment 찾는 label
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP