name: backend-cd.yml
on:
  workflow_dispatch:
  push:
    branches:
      - feature/30-backend-cd
jobs:
  deploy:
    runs-on: self-hosted
    name: "deploy to local k8s"

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Checkout kubectl context"
        run: |
          echo "Checking current context"
          kubectl config current-context
          kubectl get nodes

      - name: "Create k8s secret.yaml"
        env:
          MYSQL_DATABASE: ${{ secrets.DATABASE }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_DRIVER: ${{ secrets.SPRING_DATASOURCE_DRIVER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
          ENCRYPT_SALT: ${{ secrets.ENCRYPT_SALT }}

        run: |
          kubectl create secret generic cluster-secret --from-literal=spring_datasource_url=$env:SPRING_DATASOURCE_URL --from-literal=db_user=$env:SPRING_DATASOURCE_USERNAME --from-literal=db_password=$env:SPRING_DATASOURCE_PASSWORD --from-literal=spring_datasource_driver=$env:SPRING_DATASOURCE_DRIVER --from-literal=server_port=$env:SERVER_PORT --from-literal=encrypt_key=$env:ENCRYPT_KEY --from-literal=encrypt_salt=$env:ENCRYPT_SALT --dry-run=client -o yaml | kubectl apply -f -

      - name: "Apply k8s resources"
        working-directory: ./backend/smerp/k8s
        run: | 
          echo "Deploying backend"
          
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          
          echo "manifests applied"
          
          #--from-literal=spring_datasource_url=jdbc:mariadb://localhost:3306/$env:MYSQL_DATABASE `
