name: Frontend CI (Vue)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 저장소 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Vue 의존성 설치
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      # Vue 빌드 테스트
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      # Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t smerp-frontend ./frontend

      # (선택) 컨테이너 실행 테스트
      - name: Run container test
        run: |
          docker run -d -p 8080:80 smerp-frontend
          sleep 5
          curl -f http://localhost:8080 || exit 1
