name: frontend-ci-build.yml

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend/smerp-client
        run: npm ci

      - name: Build Vue application
        working-directory: ./frontend/smerp-client
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker 빌드 테스트 (push는 안 함)
      - name: Build Docker image (frontend)
        env:
          FRONT_DOCKER_USERNAME: ${{ secrets.FRONT_DOCKER_USERNAME }}
          FRONT_IMAGE_NAME: ${{ secrets.FRONT_IMAGE_NAME }}
        run: |
          docker build -f frontend/smerp-client/Dockerfile \
            -t $FRONT_DOCKER_USERNAME/$FRONT_IMAGE_NAME:ci-test .

      # 컨테이너가 실제로 잘 뜨는지 확인 (테스트용)
      - name: Run container test
        run: |
          docker run -d -p 8080:80 ${{ secrets.FRONT_DOCKER_USERNAME }}/${{ secrets.FRONT_IMAGE_NAME }}:ci-test
          sleep 5
          curl -f http://localhost:8080 || (docker logs $(docker ps -lq) && exit 1)
