name: frontend-ci-build.yml

on:
  push:
    branches:
      - feature/34-front-refactor

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend/smerp-client
        run: npm ci

      - name: Build Vue application
        working-directory: ./frontend/smerp-client
        run: npm run build
